# Question #2

Given the positive definite-symmetric matrix A(n*n) and vector b = [1,1,...,1] solve AX=b with the methods below for n= 5,10.

In [2]:
import numpy as np
from numpy import linalg as LA

In [3]:
M = np.diag([-1]*(5),1)+np.eye(6)*2+np.diag([-1]*(5),-1)
print(M)
print(LA.norm(M,2))

[[ 2. -1.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0. -1.  2.]]
3.801937735804838


We can see that the norm of this matrix is greater than 1 therefore given any vector X(0) it does not necessarily converge.

# jacobi

In [6]:
def jacobi(A):
    b = np.ones_like(A[0])
    x = np.zeros_like(b)
    norm = 1
    count = 0
    
    while norm > 5.0e-4:
        count += 1
        
        for i in range(A.shape[0]):
            L = np.dot(A[i, :i], x[:i])
            U = np.dot(A[i, i+1:], x[i+1:])
            x[i] = (b[i] - L - U) / A[i, i]
                
        r = np.dot(A, x) - b   
        norm = LA.norm(r, np.inf)
        if norm > 1.0e30:
            print("Norm is not converging")
            break
        
    print("Solution: " + "\n" + "{0}".format(x) + "\n" + "iteration: " + str(count))
    print("||AX - b||: " + str(norm))

In [7]:
for i in [5,10]:
    A = np.diag([-1]*(i-1),1)+np.eye(i)*2+np.diag([-1]*(i-1),-1)
    jacobi(A)
    print("-"*70)

Solution: 
[2.49919748 3.99879622 4.49879622 3.99909717 2.49954858]
iteration: 29
||AX - b||: 0.000401258523591963
----------------------------------------------------------------------
Solution: 
[ 4.99806354  8.99643449 11.99521774 13.99447716 14.99423373 14.9944673
 13.99512148 11.99611097  8.9973306   4.9986653 ]
iteration: 96
||AX - b||: 0.0004971480656337235
----------------------------------------------------------------------


# SOR

In [20]:
def sor(A, omega=0.9):
    b = np.ones_like(A[0])
    x = np.zeros_like(b)
    norm = 1
    count = 0

    while norm > 5.0e-4:
        count += 1
        x_new = np.zeros_like(x)
        
        for i in range(A.shape[0]):
            L = np.dot(A[i, :i], x_new[:i])
            U = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = ((b[i] - L - U)*omega) / A[i, i] + (1-omega)*x[i]
            
        r = np.dot(A, x) - b   
        norm = LA.norm(r, np.inf)
        if norm > 1.0e30:
            print("Norm is not converging")
            break
        x = x_new
        
    print("Solution: " + "\n" + "{0}".format(x) + "\n" + "iteration: " + str(count))
    print("||AX - b||: " + str(norm))

In [21]:
for i in [5,10]:
    A = np.diag([-1]*(i-1),1)+np.eye(i)*2+np.diag([-1]*(i-1),-1)
    sor(A)
    print("-"*70)

Solution: 
[2.49920501 3.99877232 4.49873609 3.99902409 2.49949765]
iteration: 36
||AX - b||: 0.0004987377715721664
----------------------------------------------------------------------
Solution: 
[ 4.99824866  8.99675024 11.99560733 13.9948876  14.99462071 14.99479844
 13.99537777 11.99628659  8.99743131  4.99870566]
iteration: 119
||AX - b||: 0.00048432157147004773
----------------------------------------------------------------------


By increasing the omega achieving the final result takes less iterations. Also this shows that if omega equals 1 we need less iterations but that leads us to guass-seidel method (that in this case is similar to jacobi method).

# lambda method

In [22]:
def lmethod(A, lmda=2):
    b = np.ones_like(A[0])
    x = np.zeros_like(b)
    norm = 1
    count = 0

    while norm > 5.0e-4:
        count += 1
        Ax = np.dot(A,x)
        x = x - ((Ax - b) / lmda)
            
        r = np.dot(A, x) - b   
        norm = LA.norm(r, np.inf)
        if norm > 1.0e30:
            print("Norm is not converging")
            break
        
    print("Solution: " + "\n" + "{0}".format(x) + "\n" + "iteration: " + str(count))
    print("||AX - b||: " + str(norm))

In [23]:
for i in [5,10]:
    A = np.diag([-1]*(i-1),1)+np.eye(i)*2+np.diag([-1]*(i-1),-1)
    lmethod(A)
    print("-"*70)

Solution: 
[2.49915339 3.99851843 4.49830678 3.99851843 2.49915339]
iteration: 55
||AX - b||: 0.00042330569521809025
----------------------------------------------------------------------
Solution: 
[ 4.9982972   8.99673236 11.99543224 13.99450217 14.99401751 14.99401751
 13.99450217 11.99543224  8.99673236  4.9982972 ]
iteration: 190
||AX - b||: 0.0004846660527064728
----------------------------------------------------------------------


Lambda equals 2, sounds like the best lambda in this case and the higher we go the later we get the results and the lower we go the norm does not converge.