# Question #3

Given vector b= [1,1...,1] (N^2*1) find X(j) for block matrix below where I is an identity matrix and T is a matrix as shown below. 

In [1]:
import numpy as np
from numpy import linalg as LA

In [3]:
T = np.diag([-1]*(2),1)+np.eye(3)*4+np.diag([-1]*(2),-1)
I = np.eye(3)*-1
print(T)
print(LA.norm(T,2))

[[ 4. -1.  0.]
 [-1.  4. -1.]
 [ 0. -1.  4.]]
5.414213562373095


In [4]:
A = np.block([[T,I,np.zeros((3,3))],[I,T,I],[np.zeros((3,3)),I,T]])
print(A)
print(LA.norm(A,2))

[[ 4. -1.  0. -1. -0. -0.  0.  0.  0.]
 [-1.  4. -1. -0. -1. -0.  0.  0.  0.]
 [ 0. -1.  4. -0. -0. -1.  0.  0.  0.]
 [-1. -0. -0.  4. -1.  0. -1. -0. -0.]
 [-0. -1. -0. -1.  4. -1. -0. -1. -0.]
 [-0. -0. -1.  0. -1.  4. -0. -0. -1.]
 [ 0.  0.  0. -1. -0. -0.  4. -1.  0.]
 [ 0.  0.  0. -0. -1. -0. -1.  4. -1.]
 [ 0.  0.  0. -0. -0. -1.  0. -1.  4.]]
6.828427124746191


The norm of this matrix is greater than 1 therefore given any vector X(0) it does not necessarily converge.

In [57]:
T_inv = LA.inv(T)
print(T_inv) #inverse of T

[[0.26785714 0.07142857 0.01785714]
 [0.07142857 0.28571429 0.07142857]
 [0.01785714 0.07142857 0.26785714]]


Solve AX=B with the method derived from the jacobi method.

In [61]:
x1=np.zeros(3); x2=np.zeros(3); x3=np.zeros(3)
b1=np.ones(3); b2=np.ones(3); b3=np.ones(3)

for i in range(10000):
    x1_new = np.zeros_like(x1); x2_new = np.zeros_like(x2); x3_new = np.zeros_like(x3)
    
    x1_new = np.dot(T_inv,(x2+b1))
    x2_new = np.dot(T_inv,(x1+x3+b2))
    x3_new = np.dot(T_inv,(x2+b3))
    
    norm = LA.norm((x1_new-x1))
    if norm > 1.0e30:
        print("Norm is not converging")
        break
        
    x1=x1_new; x2=x2_new; x3=x3_new

X = np.block([x1,x2,x3])
B = np.block([b1,b2,b3])
r = np.dot(A, X) - B
print("Solution: " + "\n" + "{0}".format(X))
print("error: " + "\n" + "{0}".format(r))

Solution: 
[0.6875 0.875  0.6875 0.875  1.125  0.875  0.6875 0.875  0.6875]
error: 
[ 0.00000000e+00 -4.44089210e-16 -4.44089210e-16  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.33066907e-16
 -4.44089210e-16]
