# Question #5

Using lanczos method

In [13]:
import numpy as np
from numpy import linalg as LA

In [11]:
N = int(input("enter N: "))
A = np.random.randint(-20,20,size=(N,N))
As = (A + A.T)/2

enter N: 5


In [21]:
v1 = np.random.rand(N)
v1 /= np.sqrt(np.dot(v1, v1))

In [43]:
def lanczos(A, v):
    V = np.zeros_like(A)
    T = np.zeros_like(A)
    vo = np.zeros_like(A[0])
    b = 1
    n=A.shape[0]
    
    for i in range(n-1):
        Av = np.dot(A, v)
        a = np.dot(Av, v) #transposed
        r = Av - a*v - b*vo
        b = LA.norm(r)
        vo = v
        v = r/b
        
        T[i,i] = a 
        T[i,i+1] = b
        T[i+1,i] = b
        V[i,:]   = v
        
    Av = np.dot(A, v)
    a = np.dot(Av, v)
    r = Av - a*v - b*vo
    T[n-1,n-1] = np.dot(Av, v)
    V[n-1] = r / LA.norm(r) 
    print(T)
    print('-'*80)
    print(V)
    return T

In [40]:
T = lanczos(As, v1)

[[ -9.96971147  15.39160196   0.           0.           0.        ]
 [ 15.39160196  -7.83736687  17.44463781   0.           0.        ]
 [  0.          17.44463781 -15.32615269   3.19140971   0.        ]
 [  0.           0.           3.19140971   3.08527372   7.30729673]
 [  0.           0.           0.           7.30729673   7.0479573 ]]
--------------------------------------------------------------------------------
[[-0.44698578  0.40383039  0.79707684 -0.04199833  0.00542033]
 [-0.73978829  0.11638309 -0.46573565  0.20809723  0.42302967]
 [-0.00112064 -0.36021492  0.14080123 -0.70231396  0.59764042]
 [-0.24189095 -0.81832525  0.30152509  0.41918251 -0.07211932]
 [-0.06882805  0.11443234  0.71520214 -0.44732643 -0.52014701]]


In [41]:
A_ev = LA.eigvals(As) #eigenvalues
print(A_ev)

[-34.10577376 -12.57802846  -2.25202504  13.8855769   12.05025036]


From the equation T=V(t)AV we find that T and A share the same eigenvalues.

In [42]:
T_ev = LA.eigvals(T)
print(T_ev)

[-34.10577376 -12.57802846  -2.25202504  13.8855769   12.05025036]
